version: '3.8'

services:
  postgresql_db_resource_avatars:
    image: postgres:16.4
    container_name: postgresql_db_resource_avatars
    restart: unless-stopped
    environment:      
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Test2025!
      - POSTGRES_DB=AvatarsExample
    ports: 
      - "5432:5432"